import pytest
from dbt_ls.profiles import (
    ProfileTarget,
    DuckDBTarget,
    MySQLTarget,
    Secret,
    DatabaseTarget,
    MSSQLTarget,
    SparkTarget,
    DatabricksTarget,
    AthenaTarget,
    GlueTarget,
)


@pytest.mark.parametrize(
    "target_dict, expected",
    [
        pytest.param(
            {"type": "duckdb", "threads": 1, "path": "dev.duckdb"},
            DuckDBTarget(type="duckdb", threads=1, path="dev.duckdb"),
        ),
        pytest.param(
            {
                "type": "mysql",
                "threads": 4,
                "user": "root",
                "password": "passwd",
                "server": "127.0.0.1",
                "port": 1433,
                "schema": "dev",
            },
            MySQLTarget(
                type="mysql",
                threads=4,
                user="root",
                password=Secret("passwd"),
                server="127.0.0.1",
                port=1433,
                schema="dev",
            ),
        ),
        pytest.param(
            {
                "type": "postgres",
                "threads": 4,
                "user": "postgres",
                "password": "passwd",
                "host": "127.0.0.1",
                "port": 5432,
                "schema": "dev",
                "dbname": "mydb",
            },
            DatabaseTarget(
                type="postgres",
                threads=4,
                user="postgres",
                password=Secret("passwd"),
                host="127.0.0.1",
                port=5432,
                schema="dev",
                dbname="mydb",
            ),
        ),
        pytest.param(
            {
                "type": "sqlserver",
                "threads": 4,
                "user": "sa",
                "password": "root",
                "server": "127.0.0.1",
                "port": 1234,
                "schema": "dev",
                "database": "mydb",
                "driver": "{MSSQL DRIVER}",
                "encrypt": False,
            },
            MSSQLTarget(
                type="sqlserver",
                threads=4,
                user="sa",
                password=Secret("root"),
                server="127.0.0.1",
                port=1234,
                schema="dev",
                database="mydb",
                driver="{MSSQL DRIVER}",
                encrypt=False,
            ),
        ),
        pytest.param(
            {
                "type": "spark",
                "method": "session",
                "host": "localhost",
                "schema": "default",
            },
            SparkTarget(
                type="spark", method="session", host="localhost", schema="default"
            ),
        ),
        pytest.param(
            {
                "type": "databricks",
                "catalog": "mycatalog",
                "schema": "default",
                "host": "https://adb-23452935842.2.azuredatabricks.net",
                "http_path": "/sql/1.0/warehouses/29348rw7edf",
                "token": "mytoken",
                "threads": 1,
            },
            DatabricksTarget(
                type="databricks",
                catalog="mycatalog",
                schema="default",
                host="https://adb-23452935842.2.azuredatabricks.net",
                http_path="/sql/1.0/warehouses/29348rw7edf",
                token=Secret("mytoken"),
                threads=1,
            ),
        ),
        pytest.param(
            {
                "type": "databricks",
                "catalog": "mycatalog",
                "schema": "default",
                "host": "https://adb-23452935842.2.azuredatabricks.net",
                "http_path": "/sql/1.0/warehouses/29348rw7edf",
                "client_id": "clientid123",
                "client_secret": "clientsecret123",
                "threads": 1,
            },
            DatabricksTarget(
                type="databricks",
                catalog="mycatalog",
                schema="default",
                host="https://adb-23452935842.2.azuredatabricks.net",
                http_path="/sql/1.0/warehouses/29348rw7edf",
                client_id="clientid123",
                client_secret=Secret("clientsecret123"),
                threads=1,
            ),
        ),
        pytest.param(
            {
                "type": "athena",
                "s3_staging_dir": "s3://mybucket/staging/",
                "s3_data_dir": "s3://mybucket/data/",
                "region_name": "eu-west-1",
                "schema": "dev",
                "database": "awsdatacatalog",
                "aws_profile_name": "myprofile",
                "aws_access_key_id": "AKIA123",
                "aws_secret_access_key": "secretkey123",
                "threads": 4,
            },
            AthenaTarget(
                type="athena",
                s3_staging_dir="s3://mybucket/staging/",
                s3_data_dir="s3://mybucket/data/",
                region_name="eu-west-1",
                schema="dev",
                database="awsdatacatalog",
                aws_profile_name="myprofile",
                aws_access_key_id="AKIA123",
                aws_secret_access_key=Secret("secretkey123"),
                threads=4,
            ),
        ),
        pytest.param(
            {
                "type": "glue",
                "project_name": "myproject",
                "role_arn": "arn:aws:iam::123456789012:role/GlueRole",
                "region": "eu-west-1",
                "workers": 2,
                "worker_type": "G.1X",
                "schema": "dev",
                "session_provisioning_timeout_in_seconds": 120,
                "location": "s3://mybucket/warehouse/",
                "threads": 1,
            },
            GlueTarget(
                type="glue",
                project_name="myproject",
                role_arn="arn:aws:iam::123456789012:role/GlueRole",
                region="eu-west-1",
                workers=2,
                worker_type="G.1X",
                schema="dev",
                session_provisioning_timeout_in_seconds=120,
                location="s3://mybucket/warehouse/",
                threads=1,
            ),
        ),
    ],
    ids=[
        "duckdb",
        "mysql",
        "postgres",
        "sqlserver",
        "spark",
        "databrickstoken",
        "databricksoauth",
        "athena",
        "glue",
    ],
)
def test_target_from_dict(target_dict, expected):
    assert ProfileTarget.from_dict(target_dict) == expected
